export const CATEGORY_META: Record<string, { name: string; description: string }> = {
  news: { name: "News", description: "Live newsrooms and rolling coverage" },
  sports: { name: "Sports", description: "Matches, highlights, and sports talk" },
  movies: { name: "Movies", description: "Film channels from around the world" },
  music: { name: "Music", description: "Live music, videos, and radio TV" },
  documentary: { name: "Documentary", description: "The real world, on a loop" },
  entertainment: { name: "Entertainment", description: "Variety, talk, and pop culture" },
  kids: { name: "Kids", description: "Animation and children's programming" },
  science: { name: "Science", description: "Science, space, and technology" },
  culture: { name: "Culture", description: "Art, history, and the humanities" },
  weather: { name: "Weather", description: "Forecasts and storm tracking" },
  business: { name: "Business", description: "Markets, money, and the economy" },
  education: { name: "Education", description: "Learning and public knowledge" },
  lifestyle: { name: "Lifestyle", description: "Food, fashion, home, and health" },
  travel: { name: "Travel", description: "Places, journeys, and the road" },
  series: { name: "Series", description: "Serialized drama and fiction" },
  classic: { name: "Classic", description: "Programming from earlier decades" },
  comedy: { name: "Comedy", description: "Stand-up, sitcoms, and sketches" },
  cooking: { name: "Cooking", description: "Kitchens, recipes, and food TV" },
  family: { name: "Family", description: "Something for the whole room" },
  general: { name: "General", description: "Mixed programming, all-day" },
  public: { name: "Public", description: "Public service broadcasters" },
  religious: { name: "Religious", description: "Faith and spiritual programming" },
  outdoor: { name: "Outdoor", description: "Fishing, hunting, and the wild" },
  auto: { name: "Auto", description: "Cars, bikes, and the open road" },
  animation: { name: "Animation", description: "Drawn, rendered, in motion" },
  legislative: { name: "Legislative", description: "Government and civic proceedings" },
  relax: { name: "Relax", description: "Calm pictures and quiet sound" },
  shop: { name: "Shop", description: "Home shopping and marketplace TV" },
  interactive: { name: "Interactive", description: "Audience-driven programming" },
};

export const HOME_ROW_IDS = [
  "news",
  "sports",
  "movies",
  "music",
  "documentary",
  "entertainment",
  "kids",
  "science",
  "culture",
  "weather",
] as const;

export const FEATURED_NEEDLES = [
  "al jazeera english",
  "al jazeera",
  "france 24 english",
  "france 24",
  "dw english",
  "deutsche welle",
  "nhk world",
  "bloomberg",
  "nasa tv",
  "nasa",
  "euronews",
  "sky news",
  "abc news",
  "cbs news",
  "pbs",
  "c-span",
  "bbc news",
  "bbc world",
  "cnn international",
  "cnbc",
  "arirang",
  "tv5monde",
  "rai news",
  "cgtn",
  "trt world",
  "africanews",
];

export function categoryKey(name: string): string {
  return name.trim().toLowerCase();
}
