/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as CategoryIdRouteImport } from './routes/category.$id'
import { Route as CountryCodeRouteImport } from './routes/country.$code'
import { Route as WatchChannelIdRouteImport } from './routes/watch.$channelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/country/$code',
  path: '/country/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchChannelIdRoute = WatchChannelIdRouteImport.update({
  id: '/watch/$channelId',
  path: '/watch/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/api/stream': typeof ApiStreamRoute
  '/category/$id': typeof CategoryIdRoute
  '/country/$code': typeof CountryCodeRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/api/stream': typeof ApiStreamRoute
  '/category/$id': typeof CategoryIdRoute
  '/country/$code': typeof CountryCodeRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/api/stream': typeof ApiStreamRoute
  '/category/$id': typeof CategoryIdRoute
  '/country/$code': typeof CountryCodeRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/saved'
    | '/search'
    | '/api/stream'
    | '/category/$id'
    | '/country/$code'
    | '/watch/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/saved'
    | '/search'
    | '/api/stream'
    | '/category/$id'
    | '/country/$code'
    | '/watch/$channelId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/saved'
    | '/search'
    | '/api/stream'
    | '/category/$id'
    | '/country/$code'
    | '/watch/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  ApiStreamRoute: typeof ApiStreamRoute
  CategoryIdRoute: typeof CategoryIdRoute
  CountryCodeRoute: typeof CountryCodeRoute
  WatchChannelIdRoute: typeof WatchChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$code': {
      id: '/country/$code'
      path: '/country/$code'
      fullPath: '/country/$code'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$channelId': {
      id: '/watch/$channelId'
      path: '/watch/$channelId'
      fullPath: '/watch/$channelId'
      preLoaderRoute: typeof WatchChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  ApiStreamRoute: ApiStreamRoute,
  CategoryIdRoute: CategoryIdRoute,
  CountryCodeRoute: CountryCodeRoute,
  WatchChannelIdRoute: WatchChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
